---
- name: Install tools and join realm
  hosts: txd1-deleteme.extendhealth.com
  gather_facts: no
  vars:
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"

  vars_prompt:

    - name: ansible_user
      prompt: "Enter admin username for new server"
      private: no

    - name: ansible_ssh_pass
      prompt: "Enter password (for new server)"
      private: yes
      
    - name: "bind_user"
      prompt: "AD user with access to join realm"
      private: no
      
    - name: "bind_password"
      prompt: "Password for AD user with access to join realm"
      private: yes
      #confirm: yes
      
  become: yes
  remote_user: "{{ ansible_user }}"
  become_method: sudo
    
  tasks:

  - name: Install the required packages
    yum:
#      enablerepo: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E '%{rhel}').noarch.rpm"
      name: realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,authselect-compat,python3-pip,python3-pexpect
#      ntpdate,ntp,epel-release
      state: present
    notify:
      - restart realmd
    
#  - name: Install pexpect using pip
#    pip:
#      name: pexpect
    
  - name: Join system to AD and add the computer object in the Linux OU
#    command: /bin/bash -c "echo $'{{ bind_password }}' | /usr/sbin/realm join --user={{ bind_user }} --computer-ou={{ oupath }},OU=Servers,DC=extendhealth,DC=com extendhealth.com"
    expect:
      command: /bin/bash -c "/usr/sbin/realm join --user={{ bind_user }} --computer-ou={{ oupath }},OU=Servers,DC=extendhealth,DC=com"
      responses:
        Password for *: "{{ bind_password }}"

  - name: Unrequire FQDNs
    replace:
      dest: /etc/sssd/sssd.conf
      regexp: 'use_fully_qualified_names = True'
      replace: 'use_fully_qualified_names = False'
      backup: yes
    notify:
      - restart sssd

  - name: Ignore unreadable AD GPO
    lineinfile:
      path: /etc/sssd/sssd.conf
      regexp: '^ad_gpo_ignore_unreadable ='
      line: ad_gpo_ignore_unreadable = True
    notify:
      - restart sssd

  - name: Add cache expiry to sssd.conf
    lineinfile:
      dest: /etc/sssd/sssd.conf
      line: |
        account_cache_expiration = 2
        cached_auth_timeout = 3600
        refresh_expired_interval = 4050
        
        [pam]
        reconnection_retries = 3
        offline_credentials_expiration = 2
      insertafter: '^access_provider = ad'
    notify:
      - restart sssd
        
  - name: Allow everybody to logon to the system
    command: /bin/bash -c "/usr/sbin/realm permit -a"
    
  - name: Add sudo user
    copy:
      dest: /etc/sudoers.d/91_ansible
      content: |
        svc-ansible-prod ALL=(ALL) NOPASSWD: ALL
#        {{ ansible_user }}  ALL=(ALL)  ALL
    
  - name: Add sudo groups
    copy:
      dest: /etc/sudoers.d/90_domain
      content: |
        %admin@extendhealth.com   ALL=(ALL) ALL
        %server\ administrators\ all@extendhealth.com   ALL=(ALL) ALL
        %devops\ engineer\ role@extendhealth.com   ALL=(ALL) ALL
        %site\ reliability\ engineering\ role@extendhealth.com   ALL=(ALL) ALL
        %technology\ management\ specialists\ role@extendhealth.com   ALL=(ALL) ALL
  handlers:
  - name: restart realmd
    service:
      name: realmd
      state: restarted

  - name: restart sssd
    service:
      name: sssd
      state: restarted
