---
- name: Install tools and join realm
  hosts: TBD
  become: true
  
  vars_prompt:
  - name: ansible_user
    prompt: "Enter ansible user which has sudo access"
    private: no
 
  - name: ansible_ssh_pass
    prompt: "Enter password for ansible user"
    private: yes
  
  - name: ansible_sudo_pass
    prompt: "Enter sudo password for user"
    private: yes
    
  tasks:
  - name: Install tools
    shell: sudo apt install -y realmd sssd oddjob oddjob-mkhomedir adcli samba-common samba-common-tools krb5-workstation authselect-compat
    
  - name: Discover our realm
    shell: realm discover $ad_domain
    
  - name: Join Extendhealth.com
    shell: realm join $extendhealth.com -U ${{ansible_user}}
