---
# might be more variables to consider 
production:
  hosts:
    wjp1-confluence.extendhealth.com:
    wjp1-cnfl.extendhealth.com:
    wjp1-jiralinux.extendhealth.com:
  vars:
    envir: prod
    oupath: OU=Prod

stage:
  hosts:
    wjs1-confluence.extendhealth.com:
    wjs1-cnfl.extendhealth.com:
    wjs1-jiralinux.extendhealth.com:
  vars:
    envir: stage
    oupath: OU=Stage

qa:
  hosts:
    txq1-confluence.extendhealth.com:
    txq1-cnfl.extendhealth.com:
    txq1-jiralinux.extendhealth.com:
    txq2-jiralinux.extendhealth.com:
    wjq1-jiralinux.extendhealth.com:
  vars:
    envir: qa
    oupath: OU=QA

dev:
  hosts:
    txd1-confluence.extendhealth.com:
    txd2-confluence.extendhealth.com:
    txd3-confluence.extendhealth.com:
    wjq1-conflinux.extendhealth.com:
    10.250.234.180:
    txd1-deleteme.extendhealth.com:
    txd2-domaintest:
    txd1-jiralinux.extendhealth.com:
    wjd1-jiralinux.extendhealth.com:
  vars:
    envir: dev
    oupath: OU=Dev
